name: microgel-analysis  # Give your environment a descriptive name
channels:
  - default
dependencies:
  - python=3.9   # Or your preferred Python version 
  - pip
  - pip:
    - numpy
    - pandas
    - scikit-image
    - cellpose
    - matplotlib
    - ipywidgets
    - ipyfilechooser
    - ipython
    - seaborn
    - scipy
    - jupyter
    - jupyterlab 